name: Build and Deploy Hugo to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - "infra/dev/hugoservice/**"
      - "cloudbuild/cloudbuild-docker.yaml"
      - ".github/workflows/deploy-hugo-cloudrun.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: harsha-6306683
  GCP_REGION: europe-west1
  GCS_STAGING_DIR: gs://harsha-cbbucket/cbcustom
  AR_REPO: hugo-dev-repo-docker
  IMAGE_NAME: hugo-server
  SERVICE_NAME: hugo-server

jobs:
  build:
    name: Build and Push Hugo Image
    runs-on: ubuntu-latest

    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Configure gcloud & Docker
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set compute/region $GCP_REGION
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: Compute image tag
        id: vars
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image via Cloud Build
        run: |
          gcloud builds submit \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --gcs-source-staging-dir=$GCS_STAGING_DIR \
            --config=cloudbuild/cloudbuild-docker.yaml \
            --substitutions=_TAG=${{ steps.vars.outputs.SHORT_SHA }}

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Deploy Hugo Service to Cloud Run
        env:
          SHORT_SHA: ${{ needs.build.outputs.SHORT_SHA }}
        run: |
          IMAGE_URI="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$IMAGE_NAME:${SHORT_SHA}"

          echo "Deploying image: $IMAGE_URI"

          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_URI" \
            --region "$GCP_REGION" \
            --platform managed \
            --allow-unauth \
            --port 8080 \
            --cpu 1 \
            --memory 512Mi \
            --concurrency 80 \
            --timeout 300

      - name: Show Cloud Run URL
        run: |
          URL=$(gcloud run services describe "$SERVICE_NAME" \
            --region "$GCP_REGION" \
            --format='value(status.url)')
          echo "Deployed successfully!"
          echo "URL: $URL"
