name: Build and Deploy Pact Broker to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: harsha-dev-6306683
  GCP_REGION: europe-west1
  GCS_STAGING_DIR: gs://backstage-dev-cbbucket/cbcustom
  AR_REPO: pact-dev-repo-docker
  IMAGE_NAME: pact-broker
  SERVICE_NAME: pact-broker
  # Cloud SQL instance connection string: PROJECT:REGION:INSTANCE
  CLOUDSQL_INSTANCE: harsha-dev-6306683:europe-west1:dp-pactsql-dev
  # Public base URL used by the broker when generating links (adjust if behind LB)
  PACT_BASE_URL: https://pact-broker.dev.example.co.uk

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Configure gcloud & Docker
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set compute/region $GCP_REGION
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build & Push via Cloud Build
        run: |
          gcloud builds submit \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --gcs-source-staging-dir=$GCS_STAGING_DIR \
            --config=pact-broker/cloudbuild/cloudbuild-docker.yaml \
            --substitutions=_TAG=${{ steps.vars.outputs.SHORT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Deploy Broker
        env:
          SHORT_SHA: ${{ needs.build.outputs.SHORT_SHA }}
        run: |
          IMAGE_URI="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$IMAGE_NAME:${SHORT_SHA}"
          echo "Deploying $IMAGE_URI"

          # DATABASE_URL that works on Cloud Run with Cloud SQL
          # NOTE: host=/cloudsql/<INSTANCE> makes the unix socket connection.
          DATABASE_URL="postgres://${{ secrets.PACT_DB_USER }}:${{ secrets.PACT_DB_PASS }}@/${{ secrets.PACT_DB_NAME }}?host=/cloudsql/${CLOUDSQL_INSTANCE}&sslmode=disable"

          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_URI" \
            --region "$GCP_REGION" \
            --platform managed \
            --ingress=internal-and-cloud-load-balancing \
            --no-allow-unauthenticated \
            --port 8080 \
            --cpu 1 \
            --memory 1Gi \
            --concurrency 80 \
            --timeout 600 \
            --add-cloudsql-instances "$CLOUDSQL_INSTANCE" \
            --set-env-vars "PORT=8080" \
            --set-env-vars "PACT_BROKER_PORT=8080" \
            --set-env-vars "PACT_BROKER_DATABASE_URL=${DATABASE_URL}" \
            --set-env-vars "PACT_BROKER_BASE_URL=${PACT_BASE_URL}" \
            --set-env-vars "PACT_BROKER_LOG_LEVEL=INFO"

      - name: Show URL
        run: |
          URL=$(gcloud run services describe "$SERVICE_NAME" --region "$GCP_REGION" --format='value(status.url)')
          echo "Deployed: $URL"
