name: Build and Deploy Pact Broker to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: harsha-dev-6306683
  GCP_REGION: europe-west1
  GCS_STAGING_DIR: gs://backstage-dev-cbbucket/cbcustom
  AR_REPO: pact-dev-repo-docker
  IMAGE_NAME: pact-broker
  SERVICE_NAME: pact-broker
  CLOUDSQL_INSTANCE: harsha-dev-6306683:europe-west1:dp-pactsql-dev
  PACT_BASE_URL: https://pact-broker.dev.example.co.uk

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: dev   # <-- uncomment if your creds secret is under the 'dev' Environment
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}

    steps:
      - uses: actions/checkout@v4

      # ---- Secret validation (build auth creds) ----
      - name: Validate required secrets for build
        shell: bash
        run: |
          missing=0
          if [ -z "${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}" ]; then
            echo "::error title=Missing secret::DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS is not set"
            missing=1
          fi
          if [ $missing -ne 0 ]; then
            echo "Required build secrets are missing. Exiting."
            exit 1
          fi

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Configure gcloud & Docker
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set compute/region $GCP_REGION
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Ensure EU staging bucket exists
        run: |
          gsutil ls -b $GCS_STAGING_DIR || \
            gsutil mb -l $GCP_REGION $GCS_STAGING_DIR

      - name: Build & Push via Cloud Build
        run: |
          gcloud builds submit \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --gcs-source-staging-dir=$GCS_STAGING_DIR \
            --config=pact-broker/cloudbuild/cloudbuild-docker.yaml \
            --substitutions=_TAG=${{ steps.vars.outputs.SHORT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # environment: dev   # <-- uncomment if your DB secrets are under the 'dev' Environment
    steps:
      # ---- Secret validation (DB creds) ----
      - name: Validate required secrets for deploy
        shell: bash
        run: |
          missing=0
          if [ -z "${{ secrets.PACT_DB_USER }}" ]; then
            echo "::error title=Missing secret::PACT_DB_USER is not set"; missing=1; fi
          if [ -z "${{ secrets.PACT_DB_PASS }}" ]; then
            echo "::error title=Missing secret::PACT_DB_PASS is not set"; missing=1; fi
          if [ -z "${{ secrets.PACT_DB_NAME }}" ]; then
            echo "::warning title=Defaulting DB name::PACT_DB_NAME not set, will default to 'postgres'"; fi
          # Optional sanity checks (non-failing):
          if [[ "${{ secrets.PACT_DB_USER }}" =~ [/:@?#\[\]%] ]]; then
            echo "::warning title=Username contains URI-reserved chars::User contains characters that could require encoding in URLs."
          fi
          if [ $missing -ne 0 ]; then
            echo "Required deploy secrets are missing. Exiting."
            exit 1
          fi

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Configure gcloud
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set compute/region $GCP_REGION

      # Encode DB password for safe use in DATABASE_URL
      - name: Encode DB password
        run: |
          ENCODED_PASS=$(python3 - <<'PY'
import os, urllib.parse
print(urllib.parse.quote(os.environ["PACT_DB_PASS"]))
PY
)
          echo "ENCODED_PASS=$ENCODED_PASS" >> $GITHUB_ENV
        env:
          PACT_DB_PASS: ${{ secrets.PACT_DB_PASS }}

      - name: Deploy Pact Broker to Cloud Run
        env:
          SHORT_SHA: ${{ needs.build.outputs.SHORT_SHA }}
        run: |
          IMAGE_URI="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$IMAGE_NAME:${SHORT_SHA}"
          echo "Deploying $IMAGE_URI"

          DBNAME="${{ secrets.PACT_DB_NAME }}"
          if [ -z "$DBNAME" ]; then DBNAME=postgres; fi

          # Cloud SQL unix-socket connection URI (password already URL-encoded)
          DATABASE_URL="postgres://${{ secrets.PACT_DB_USER }}:${ENCODED_PASS}@/cloudsql/${CLOUDSQL_INSTANCE}/${DBNAME}"

          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_URI" \
            --region "$GCP_REGION" \
            --platform managed \
            --ingress=internal-and-cloud-load-balancing \
            --no-allow-unauthenticated \
            --port 8080 \
            --cpu 1 \
            --memory 1Gi \
            --concurrency 80 \
            --timeout 600 \
            --add-cloudsql-instances "$CLOUDSQL_INSTANCE" \
            --set-env-vars "PORT=8080" \
            --set-env-vars "PACT_BROKER_PORT=8080" \
            --set-env-vars "PACT_BROKER_DATABASE_URL=${DATABASE_URL}" \
            --set-env-vars "PACT_BROKER_BASE_URL=${PACT_BASE_URL}" \
            --set-env-vars "PACT_BROKER_LOG_LEVEL=INFO"

      - name: Show URL
        run: |
          URL=$(gcloud run services describe "$SERVICE_NAME" --region "$GCP_REGION" --format='value(status.url)')
          echo "Deployed: $URL"
