name: Build and Deploy Hugo to Cloud Run
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/DTP-3683-1

permissions:
  id-token: write
  contents: read

env:
  # GCP / Artifact Registry / Cloud Run
  GCP_PROJECT_ID: bguk-backstage-dev-6306683
  GCP_REGION: europe-west1
  GCS_STAGING_DIR: gs://backstage-dev-cbbucket/cbcustom
  AR_REPO: hugo-dev-repo-docker
  IMAGE_NAME: hugo-server
  SERVICE_NAME: hugo-server

  # ---- Content repo (learning-pathway) ----
  CONTENT_REPO: Blu-Technical-Platform/dtp-learning-pathway
  CONTENT_REF: main
  BASE_URL: "https://digital-platform-learning.bupa.co.uk/"

jobs:
  build:
    name: Build and Push Image (with learning-pathway content)
    runs-on: ubuntu-latest
    outputs:
      SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
    steps:
      - name: Checkout this repo (hugo-service)
        uses: actions/checkout@v4

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.LEARNING_PATH_APP_ID }}
          private-key: ${{ secrets.LEARNING_PATH_APP_PRIVATE_KEY }}
          owner: Blu-Technical-Platform
          repositories: dtp-learning-pathway

      - name: Checkout learning-pathway (content + themes)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CONTENT_REPO }}
          ref: ${{ env.CONTENT_REF }}
          path: dtp-learning-pathway
          token: ${{ steps.app-token.outputs.token }}

      # --- Verify dtp-learning-pathway clone succeeded ---
      - name: Verify dtp-learning-pathway clone
        run: |
          echo "Current working directory: $PWD"
          echo "Listing top-level folders:"
          ls -la
          echo "------------------------------------"
          if [ -d "dtp-learning-pathway" ]; then
            echo "'dtp-learning-pathway' folder exists"
            cd dtp-learning-pathway
            echo "-- Git status --"
            git status
            git rev-parse --is-inside-work-tree
            git remote -v
            echo "== Top-level files and folders =="
            ls -la
            echo "== Three-level directory tree =="
            find . -maxdepth 3 -type d -print
          else
            echo "'dtp-learning-pathway' folder not found -- checkout failed!"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi

      - name: Assemble Hugo site layout
        run: |
          set -eup pipefail
          echo "Starting assemble..."
          mkdir -p site
          echo "Copying dtp-gcp-learning -> site"
          if [ -d "dtp-learning-pathway/gcp-learning" ]; then
            rsync -av --ignore-errors --exclude '.git/' --stats "dtp-learning-pathway/gcp-learning/" site/
          else
            echo "'dtp-learning-pathway/gcp-learning' folder not found"
            find dtp-learning-pathway -maxdepth 2 -type d -print
            exit 2
          fi
          echo "Copying themes -> site/themes"
          if [ -d "dtp-learning-pathway/themes" ]; then
            mkdir -p site/themes
            rsync -av --ignore-errors --exclude '.git/' --stats "dtp-learning-pathway/themes/" site/themes/
          else
            echo "No themes folder found under learning-pathway/"
          fi
          echo "Final site structure:"
          find site -maxdepth 3 -type d -print
          echo "Config files present in site:"
          ls -la site | egrep 'hugo\.toml|config\.toml|config\.yaml' || true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Configure gcloud & Docker
        run: |
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set compute/region $GCP_REGION
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: Compute image tag
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Push via Cloud Build
        run: |
          gcloud builds submit \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --gcs-source-staging-dir=$GCS_STAGING_DIR \
            --config=cloudbuild/cloudbuild-docker.yaml \
            --substitutions=_TAG=${{ steps.vars.outputs.SHORT_SHA }}

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DIGITAL_PLATFORM_PORTAL_GCS_CREDENTIALS }}

      - name: Deploy Hugo Service to Cloud Run
        env:
          SHORT_SHA: ${{ needs.build.outputs.SHORT_SHA }}
        run: |
          IMAGE_URI="$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO/$IMAGE_NAME:${SHORT_SHA}"
          echo "Deploying $IMAGE_URI"
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE_URI" \
            --region "$GCP_REGION" \
            --platform managed \
            --project "$GCP_PROJECT_ID" \
            --no-allow-unauthenticated \
            --port 8080 \
            --cpu 1 \
            --memory 512Mi \
            --concurrency 80 \
            --timeout 300

      - name: Show Cloud Run URL
        run: |
          URL=$(gcloud run services describe "$SERVICE_NAME" --region "$GCP_REGION" --format='value(status.url)')
          echo "Deployed successfully"
          echo "URL: $URL"
